# Generated by Django 4.2.7 on 2023-12-08 20:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("server", "0002_alter_server_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.RemoveField(
            model_name="server",
            name="members",
        ),
        migrations.AddField(
            model_name="server",
            name="member",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
